name = "gpsc-v2"
main = "src/index.js"
compatibility_date = "2024-12-01"

[vars]
BOT_TOKEN = "8348112817:AAGvM1vYArITu6Ru_iH6IPqHFnmaBw6NJbM"

[[kv_namespaces]]
binding = "KV"
id = "1a154163dd614f8da7d889b5aa04701b"

[[d1_databases]]
binding = "DB"
database_name = "gpsc_dental"
database_id = "5d374e7d-2d0f-4c7e-87ae-aa2e2f949515"
